name: Generer de la JavaDoc avec une IA Ollama

permissions:
  contents: write

on:
  push:
    branches: [main]
    paths:
      - "git/borne_arcade/*.java"
  workflow_dispatch:

jobs:
  generate-doc:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        persist-credentials: true

    - name: Install Java
      uses: actions/setup-java@v4
      with: 
        distribution: temurin
        java-version: 21


    - name: Install Ollama
      if: steps.changed.outputs.files != ''
      run: curl -fsSL https://ollama.com/install.sh | s

     - name: Start Ollama
      if: steps.changed.outputs.files != ''
      run: |
        ollama serve &
        sleep 5

    - name: Pull model
      if: steps.changed.outputs.files != ''
      run: ollama pull deepseek-coder:6.7b

    - name: Get modified Java files
      id: modified-files
      uses: GrantBirki/git-diff-action@v1
      with:
        json_diff_file_output: diff.json
        file_output_only: "true"

    - name: Set modified Java files
      id: java-files
      run: |
        FILES=$(jq -r '.[] | select(.filename|test("^git/borne_arcade/[^/]+\\.java$")) | .filename' diff.json)
        echo "Modified Java files: $FILES"
        echo "::set-output name=files::$FILES"h

    - name: Compile project
      working-directory: git/borne_arcade
      run: |
        for f in ${{ steps.java-files.outputs.files }}; do
          echo "Processing $f"
          javac -cp "libs/javaparser-core-3.25.10.jar:." "$(basename $f)"
          java -cp "libs/javaparser-core-3.25.10.jar:." GenerateDoc "$(basename $f)"
        done

    - name: Commit changes
      if: steps.changed.outputs.files != ''
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Génération automatique de documentation" || echo "Rien à modifier"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/AtoupikK/SAE_Maintenance_Logicielle.git HEAD:main
