name: Generer de la JavaDoc avec une IA Ollama

permissions:
  contents: write

on:
  push:
    branches: [main]
    paths:
      - "git/borne_arcade/*.java"
  workflow_dispatch:

jobs:
  generate-doc:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Install Java
      uses: actions/setup-java@v4
      with: 
        distribution: temurin
        java-version: 21

    - name: Get modified Java files
      id: changed
      run: |
      FILES=$(jq -r '.commits[].modified + .commits[].added | .[]' "$GITHUB_EVENT_PATH" \
      | grep "^git/borne_arcade/[^/]*\.java$" || true)
    echo "FILES=$FILES" >> $GITHUB_ENV


    - name: Install Ollama
      if: steps.changed.outputs.files != ''
      run: curl -fsSL https://ollama.com/install.sh | sh

    - name: Start Ollama
      if: steps.changed.outputs.files != ''
      run: |
        ollama serve &
        sleep 5

    - name: Pull model
      if: steps.changed.outputs.files != ''
      run: ollama pull deepseek-coder:6.7b

    - name: Compile project
      if: steps.changed.outputs.files != ''
      working-directory: git/borne_arcade
      run: javac -cp "libs/javaparser-core-3.25.10.jar:." GenerateDoc.java

    - name: Run doc generator
      if: steps.changed.outputs.files != ''
      working-directory: git/borne_arcade
      run: java -cp "libs/javaparser-core-3.25.10.jar:." GenerateDoc

    - name: Commit changes
      if: steps.changed.outputs.files != ''
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Génération automatique de documentation" || echo "Rien à modifier"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/AtoupikK/SAE_Maintenance_Logicielle.git HEAD:main
